#!/usr/bin/env bash
## Run gatsby develop
# Usage: fin develop
#: exec_target = cli

set -e
# Source the profile to enable nvm.
. ~/.profile

##################################################################
##### Run NPM commands against the API.
##################################################################
if [ -e ${GATSBY_APPLICATION_PATH} ]; then
    cd ${GATSBY_APPLICATION_PATH} && \
    gatsby "$@"
else
    printf "\n$FATAL_SLUG ${GATSBY_APPLICATION_PATH} does not exist.\n"
fi